server:
  port: 8005

grpc:
  server:
    port: 9005
  client:
    gongik-life-client-be-auth-service:
      address: 'discovery:///gongik-life-client-be-auth-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    gongik-life-client-be-user-service:
      address: 'discovery:///gongik-life-client-be-user-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    gongik-life-client-be-community-service:
      address: 'discovery:///gongik-life-client-be-community-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    gongik-life-client-be-institution-service:
      address: 'discovery:///gongik-life-client-be-institution-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    gongik-life-client-be-notification-service:
      address: 'discovery:///gongik-life-client-be-notification-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    gongik-life-client-be-report-service:
      address: 'discovery:///gongik-life-client-be-report-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    gongik-life-client-be-workhours-service:
      address: 'discovery:///gongik-life-client-be-workhours-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  application:
    name: gongik-life-client-be-institution-service

  datasource:
    url: jdbc:postgresql://localhost:5432/gongik_life_client_institution_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
    elasticsearch:
      repositories:
        enabled: true
      url: localhost:9200

  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gongik-life-client-be-institution-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  batch:
    jdbc:
      initialize-schema: always



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true
    fetchRegistry: true

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - loggers
          - mappings
          - metrics
          - shutdown
          - prometheus

logging:
  level:
    root: INFO
    org.example.gongiklifeclientbeinstitutionservice: DEBUG
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
