### Sign In User
POST http://localhost:8001/api/auth/signIn
Content-Type: application/json

{
  "email": "1@92.com",
  "password": "1234"
}


### Validate Access Token
POST http://localhost:8001/api/auth/validateAccessToken
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZDQ1MWFjYy01MzZjLTRmZGQtYTY1Ni04ZWU5MGMxMTM0MDkiLCJpYXQiOjE3MzY3NjM1MjEsImV4cCI6MTczNjc2NTMyMX0.b-jINrqKa6uo0HCMgxBy9qm2tCHT1BbJcrNJWNst6t9oqTHL1e78MB6zI1vB5bsr

//{
//  "accessToken": "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIzZTA5N2U4YS02MjU1LTRjNTMtYjljOS0zMTRlZGFkMTYxOGYiLCJpYXQiOjE3MzY3MDMzNzAsImV4cCI6MTczNjcwNTE3MH0.NQbdD4-9y044LZQRULklRMamSr2XM0L764NhrvsBhyFQHXv8k0rghdQJJPwzgbXF"
//}


### Refresh Access Token
POST http://localhost:8001/api/auth/refreshAccessToken
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIzZTA5N2U4YS02MjU1LTRjNTMtYjljOS0zMTRlZGFkMTYxOGYiLCJpYXQiOjE3MzY3MDY2MjksImV4cCI6MTczNzkxNjIyOX0.Stowo3gO2R_PGv3Stt06mdF9n6vTxPLcE7Oj_QQTBZuy5J8t1-BI5HwmVfMYoRzO

{
}

### Sign Out
POST http://localhost:8001/api/auth/signOut
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIzZTA5N2U4YS02MjU1LTRjNTMtYjljOS0zMTRlZGFkMTYxOGYiLCJpYXQiOjE3MzY3MDY2MjksImV4cCI6MTczNzkxNjIyOX0.Stowo3gO2R_PGv3Stt06mdF9n6vTxPLcE7Oj_QQTBZuy5J8t1-BI5HwmVfMYoRzO

{
}


