server:
  port: 8000

spring:
  application:
    name: gongik-life-client-be-discovery

eureka:
  instance:
    hostname: gongik-life-client-be-discovery
    registry:
      default-open-for-traffic-count: 1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    region: default
  server:
    renewal-percent-threshold: 0
    enable-self-preservation: true


management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - loggers
          - mappings
          - metrics
          - shutdown
          - prometheus